# -*- coding: utf-8 -*-
"""
Created on Fri Aug 24 21:23:03 2018

@author: bettmensch
"""

import numpy as np

# --- dimensions
WINDOW_WIDTH_PIXELS = 400
WINDOW_HEIGHT_PIXELS = 400

TILE_HEIGHT = TILE_WIDTH = 20
WINDOW_WIDTH = int(WINDOW_WIDTH_PIXELS / TILE_WIDTH)
WINDOW_HEIGHT = int(WINDOW_HEIGHT_PIXELS / TILE_HEIGHT)

# --- speed
FPS = 40

# --- visuals
BLUE = (0,0,255)
GREEN = (0,255,0)
RED = (255,0,0)
BLACK = (0,0,0)
WHITE = (255,255,255)

# --- game constants
UP = 'UP'
RIGHT = 'RIGHT'
LEFT = 'LEFT'
DOWN = 'DOWN'
NOTHING = 'NOTHING'
QUIT_GAME = 'QUIT_GAME'
SNAKE_INIT_LENGTH = 5
FONT_SIZE = 20
SCORE_OFF_X = WINDOW_WIDTH_PIXELS - TILE_WIDTH
SCORE_OFF_Y = TILE_HEIGHT

# --- AI constants
MAX_FRAMES = 1000
SNAKE_VALUE = 1
FOOD_VALUE = -1
DIRECTION_VALUE = 1
DIRECTION_TEMPLATE = np.array([UP,RIGHT,DOWN,LEFT]).reshape((1,-1))
N1 = 100
N2 = 100
N3 = 4
DROPOUTRATE1 = 0.4
DROPOUTRATE2 = 0.4